{
 "title": "Snapchain",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "stats.gauges.*.shard*.block_height"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Propose",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "targets": [
    { "target": "stats_counts.*.shard*.propose" }
   ]
  },
  {
   "title": "Validate False",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "target": "stats_counts.*.shard*.validate.false"
    }
   ]
  },
  {
   "title": "Validate True",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "target": "stats_counts.*.shard*.validate.true"
    }
   ]
  }
 ]
}